// <auto-generated />
using System;
using CatalogService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogService.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20230425122725_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("2aceae56-c4ef-4bd3-bd8f-879b93288cd1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 4, 24, 12, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Name = "Blue Pencil",
                            UnitPrice = 4.99m
                        },
                        new
                        {
                            ProductId = new Guid("515718c9-4f7f-4014-9b54-8cd3c32e08d9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 4, 24, 12, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Name = "Red Notepad",
                            UnitPrice = 7.49m
                        },
                        new
                        {
                            ProductId = new Guid("c3d7bb4d-7c63-4ede-b6c9-365c362e884c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 4, 24, 12, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            Name = "White Eraser",
                            UnitPrice = 3.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
